app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255), nullable=False, unique=True)
    email = db.Column(db.String(255),nullable=True,unique=True)
    password = db.Column(db.String(255), nullable=False)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    blogs = db.relationship('Blog', backref='blogyou',lazy=True)
    comment = db.relationship('Comments', backref='commenting',lazy=True)


    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def set_password(self,password):
        password_hash = generate_password_hash(password)
        self.password = password_hash

    def check_password(self,password):
        return check_password_hash(self.password,password)

    def __repr__(self):
        return "User: %s"%str(self.username)


@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(user_id)


class Blog(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(100),nullable=False)
    date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    blog = db.Column(db.Text,nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)
    comment_it = db.relationship('Comments', backref='user_comment',lazy=True)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


    def __repr__(self):
        return f"Blog('{self.title}', '{self.date_posted}')"




class Comments(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.String(255),nullable=False)
    date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

class Subscribe(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(100))
    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()
    def __repr__(self):
        return f"Comments('{self.email}')"


class Quotes:
    def __init__(self,author,quote,permalink):
        self.author = author
        self.quote = quote
        self.permalink = permalink

app/__init__.py
from flask import Flask
from config import configurations
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES

app =  Flask(__name__)
db = SQLAlchemy(app)
mail = Mail(app)
login_manager = LoginManager(app)
login_manager.login_view ='auth.login'
login_manager.session_protection = "strong"
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app.config.from_object(configurations[config_name])
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    db.init_app(app)
    mail.init_app(app)
    configure_uploads(app,photos)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from .views import *

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from app.models import User,Blog, Comments, Quotes, Subscribe
from flask_login import login_user,login_required, logout_user,current_user
import requests
from .. import mail, db,photos
from ..email import mail_message
from flask_mail import Message


response = requests.get('http://quotes.stormconsultancy.co.uk/random.json')
quotes = response.json()
author = quotes.get('author')
quote = quotes.get('quote')
permalink = quotes.get('permalink')
quoty = Quotes(author,quote,permalink)


@main.route('/')
def home():
    title = "YUBlog"
    blogs = Blog.query.all()
    comment = Comments.query.all()
    quote = quoty
    print(quotes)
    return render_template('index.html', title=title,blogs=blogs,comment=comment, quote=quote)

@main.route('/blogs', methods=['POST','GET'])
@login_required
def blogs():
    if request.method == 'POST':
        form = request.form
        title = form.get('title')
        blog = form.get('blog')
        if title==None or blog==None:
            error = "All fields are required"
            return render_template('create_blog.html', error=error)
        blog = Blog(title=title,blog=blog, user_id=current_user.id)
        blog.save()
        subscribers = Subscribe.query.all()
        for subscriber in subscribers:
            mail_message("Hello,New Blog has been created", "email/new_blog",subscriber.email,blog=blog)
        return redirect(url_for('main.home'))
    return render_template('create_blog.html')


@main.route('/delete/<int:comment_id>')
@login_required
def delete(comment_id):
    comm = Comments.query.get(comment_id)
    comm.delete()
    return redirect(url_for('main.home'))


@main.route('/del/<int:blog_id>', methods=['POST','GET'])
@login_required
def del_blog(blog_id):
    blog = Blog.query.get(blog_id)
    blog.delete()
    return redirect(url_for('main.home'))


@main.route('/comment/<int:blog_id>', methods=['GET','POST'])
def comment(blog_id):
    if request.method == 'POST':
        comment = request.form.get('comment')
        blog = Blog.query.filter_by(id=blog_id).first()
        comment = Comments(comment=comment,blog_id=blog.id)
        comment.save()
        return redirect(url_for('main.home',blog=blog))
    return render_template('index.html')

@main.route('/subscribe', methods=['GET','POST'])
def subscribe():
    if request.method == "POST":
        form = request.form
        email = form.get("email")
        if email==None:
            error = "Enter your email required"
            return render_template('index.html', error=error)
        user = Subscribe(email=email)
        user.save()
        users = Subscribe.query.all()
        for user in users:
            mail_message("Hello", "email/subscribe",user.email,user=user)
        return redirect(url_for("main.home"))
    return render_template('index.html')


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    blogs = Blog.query.filter_by(user_id= current_user.id).all()
    return render_template("profile/profile.html", user=user, blogs=blogs)



@main.route('/user/<uname>/update', methods=['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    if request.method == "POST":
        user.bio = request.form.get('bio')
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.profile',uname=user.username))
    return render_template('profile/profile.html', user=user)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'images/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% block styles%}
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body>
    {%block navbar %}
      {% include 'navbar.html' %}
    {% endblock %}
    {% block content%}
      <div class="container-fluid">




      </div>
    {% endblock %}
    <!-- <footer>
      <div class="container-fluid mt-5 bg-dark">
        <div class="row  bg-danger">
          <div class="col-md-4">
            <p class="text-center text-white mt-3">&copy; IreneMercy</p>
          </div>
          <div class="col-md-4">
            <h4 class="text-white mt-2">Contact</h4>
            <p class="text-white">Email~ irenemercy700@gmail.com</p>
            <p class="text-white">Github~ IreneMercy</p>
          </div>
          <div class="col-md-4">
            <ul class="navbar-nav ml-auto">
              <h4 class="mt-3 text-white">Quick Links</h4>
              {% if current_user.is_authenticated  %}
                <li class="nav-item text-white ml-2"><a class="mt-5 text-white items" href="{{url_for('main.home')}}">{{current_user.username}}</a></li>
                <li><a class="text-white ml-2 items" href="{{url_for('main.blogs')}}">CreateBlog</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </footer> -->
  {% block script%}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% endblock %}
  </body>
</html>

app/templates/create_blog.html
{% extends 'base.html' %}

{% block content %}
  {{super()}}
  <div class="container">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4 mt-4 blog">
        <div class="card bg-dark text-white">
          <form action="/blogs" method="POST">
          <div class="card-header">
            {% if error %}
              <p class="alert-alert-danger text-center mt-2 bg-danger">
                {{error}}
              </p>
            {% endif %}
          </div>
          <div class="card-body">
            <div class="text-center">
              <p>Create a blog</p>
              <hr>
              <input size="50cl" type="text" placeholder="Title" name="title" required>
              <br>
              <br>
              <textarea type="text" name="blog" rows="5" cols="50" placeholder="Write a blog" required></textarea>
              <br>
              <input type="submit" value="Submit" class="btn btn-btn-lg bg-danger text-uppercase mt-5 w-50 text-white">
            </div>

          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/index.html
{% include 'base.html' %}
{% block content%}
<div class="container home">
<div class="row">
  <div class="col-md-6">
    <div class="col-md-8">
      <p class="mt-3">{{quote.quote}}</p>
    </div>
    <form class="mt-5 ml-3" action="/subscribe" method='POST'>
      <h4>Subscribe</h4>
      <input type="text" name="email" value="Enter email">
      <br>
      <input class="btn btn-danger mt-1" type="submit" value="Submit">
    </form>
  </div>
      {% for blog in blogs%}
      <div class="col-md-6 mt-3">
        <div class="card">
          <div class="card-title mt-5 ml-3 text-uppercase">
            <h5>{{blog.title}}</h5>
          </div>
          <div class="card-body">
            <p>{{blog.blog}}</p>
          </div>
          <div class="card-body">
            <p>{{blog.date_posted.strftime('%Y-%m-%d')}} {{blog.blogyou.username}}</p>
            {%  if current_user == blog.blogyou %}
            <a class="text-danger" href="{{url_for('main.del_blog',blog_id=blog.id)}}">DeleteBlog</a>
            {% endif %}
            <h4 class="mt-3">Comments</h4>
            {% for comm in comment %}
              {% if blog.id == comm.blog_id %}
                <p>{{comm.comment}}</p>
                <p>{{comm.date_posted.strftime('%y-%m-%d')}}</p>

                {%  if current_user == blog.blogyou %}
                <a class="text-danger" href="{{url_for('main.delete',comment_id=comm.id)}}">DeleteComment</a>
                {% endif %}
              {% endif %}
            {% endfor %}
            <form  class="mt-3" action="{{url_for('main.comment',blog_id=blog.id)}}" method="post">
              <input type="text" name="comment" class="w-100">
              <input type="submit" value="Comment" class="btn btn-danger mt-1">
            </form>
          </div>
        </div>
      </div>

      {% endfor %}


  </div>
</div>
{%  endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  {{super()}}
  <div class="container">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4 mt-4 login">
        <div class="card bg-dark text-white">
          <form action="/login" method="POST">
          <div class="card-header">
            {% if error %}
              <p class="alert-alert-danger text-center mt-2 bg-danger">
                {{error}}
              </p>
            {% endif %}
          </div>
          <div class="card-body">
            <div class="text-center">
              <h1 class="mt-5">Login</h1>
              <p>Please fill in this form to login.</p>
              <hr>

              <input size="30cl" type="text" placeholder="Enter Username" name="username" required>
              <br>
              <br>
              <input size="30cl" type="password" placeholder="Enter Password" name="password" required>
              <br>
              <input type="submit" value="Login" class="btn btn-btn-lg bg-danger text-uppercase mt-5 w-50 text-white">
            </div>
            <div class="card-footer mt-3">
              <p class="text-center">Don't have an account?? <a href="{{url_for('auth.signup')}}">Signup</a></p>
            </div>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/navbar.html
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg bg-danger sticky-top">
    <a class="navbar-brand text-white link" href="{{url_for('main.home')}}"font-size="20px">BlogYU</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated  %}
            <li class="nav-item text-white ml-2"><a class="mt-5 text-white items" href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
            <li><a class="text-white ml-2 items" href="{{url_for('main.blogs')}}">CreateBlog</a></li>
            <li><a class="text-white ml-2 items" href="{{url_for('auth.logout')}}">Logout</a></li>
          {% if current_user.is_authenticated and current_user.profile_pic_path is none %}
          {% endif %}
          {% else %}
            <li class="nav-item"><a class="nav-link text-white" href="{{url_for('auth.login')}}">Login</a></li>

          {% endif %}
        </ul>
    </div>

  </nav>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}


{% block content%}
<div class="container profile">
  <div class="row profile">
    <div class="col-md-4 profile">
      <h3 class="mt-3">{{user.username}}</h3>
      {% if user.profile_pic_path %}
      <img src="{{url_for('static', filename= user.profile_pic_path)}}" alt="" class="rounded-circle card-image mt-3" width="36%" height="40%">
      {% else %}
      <p class="mt-3">No profile picture</p>
      {% endif %}
      <br>
      <br>
      {% if user.bio %}
        ~ {{user.bio}}
        {% else %}
        <p>{{user.username}} has no bio</p>
      {% endif %}
    </div>
    <div class="col-md-4 profile mt-3">
      <h4>Blogs</h4>
      <br>
      {% if blogs %}
        {% for blog in blogs%}
          <div class="card mt-3">
            <div class="card-header">
              <a href="{{url_for('main.home')}}">{{blog.title}}</a>
            </div>
          </div>
        {% endfor %}
      {% else %}
      <p>No blogs</p>
      {% endif %}
    </div>
    <div class="col-md-4 profile">
      <h4 class="mt-3">Update Profile</h4>
      <form class="mt-5" action="{{url_for('main.update_pic',uname=current_user.username)}}" method="post" enctype = "multipart/form-data">
          <input type="file"  name="photo" class="form-control ml-3" required>
          <input class="btn btn-danger mt-2 ml-3" type="submit">
        </form>
        <br>
      <form action="{{url_for('main.update_profile',uname=current_user.username)}}" method="POST">
         {% if error %}
           <p class="alert-alert-danger text-center  bg-danger error">
             {{error}}
           </p>
         {% endif %}
       <div class="container text-center">
         <textarea type="text"  name="bio" class="form-control ml-1" placeholder="Tell us more about you" required></textarea>
         <input class="btn btn-danger w-100 mt-2 ml-1" type="submit">
       </div>
       </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  {{super()}}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <div class="card mt-3 bg-dark signup text-white">
          <form action="/signup" method="POST">
            <div class="card-header">
              {% if error %}
                <p class="alert-alert-danger text-center mt-2 bg-danger">
                  {{error}}
                </p>
              {% endif %}
            </div>
            <div class="card-body">
              <div class="container text-center">
                <h1 class="mt-5">Sign Up</h1>
                <p>Please fill in this form to create an account.</p>
                <hr>

                <input size="35cl" class=" border-outline-info" type="text" placeholder="Enter Username" name="username" required>
                <br>
                <br>
                <input size="35cl" type="text" placeholder="Enter Email" name="email" required>
                <br>
                <br>
                <input size="35cl" type="password" placeholder="Enter Password" name="password" required>
                <br>
                <br>
                <input size="35cl" type="password" placeholder="ConfirmPassword" name="confirm_password" required>
                <br>
                <input type="submit" value="signup" class="btn btn-btn-lg bg-danger mt-5 w-50 text-white">
              </div>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}